# Generated by Django 2.2.3 on 2019-07-27 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190727_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 16, 7, 34, 256220)),
        ),
    ]
