# Generated by Django 2.2.3 on 2019-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190727_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(default='django-db-models-fields-charfield', max_length=250, unique=True),
        ),
    ]
