# Generated by Django 2.2.3 on 2019-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190727_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_status',
            field=models.BooleanField(default=True, verbose_name='Publish?'),
        ),
    ]
