# Generated by Django 2.2.3 on 2019-07-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
