# Generated by Django 2.2.3 on 2019-08-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190730_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_fixed',
            field=models.BooleanField(default=False, verbose_name='Use as fixed post'),
        ),
    ]
